### ISSUE TITLE
Enable a --fx option?

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-csharp#14]
In #12 we are discussing the idea of having a switch `--fx`` where users can specify the target framework version for the created project.

If passed the value would simply populate the `<TargetFramework>` element in the .csproj file. This would be similar to the [`--gulp`](https://github.com/OmniSharp/generator-aspnet/blob/409072e61d3aa76d655dac8458f73e4bb3816671/app/index.js#L152) option available in the [asp.net 5 yo generators](https://github.com/OmniSharp/generator-aspnet).

Thoughts?

**Comment by shmuelie** [comment]
Would anything else have to change besides `<TargetFramework>`?

**Comment by sayedihashimi** [comment]
Since the templates are pretty vanilla I expect they should build with most recent versions so I doubt it. We should verify that they build/run.

**Comment by shmuelie** [comment]
First thing I can think of is that if you use a framework earlier than 3.5 `using System.Linq;` won't compile

**Comment by sayedihashimi** [comment]
OK I see, in that case we may need to have some conditional content in the templates then to support this.

**Comment by sayedihashimi** [comment]
We should just remove that from the template. Both VS and OmniSharp has easy ways to add missing using statements.

**Comment by shmuelie** [comment]
Ok

**Comment by SamuelEnglard** [comment]
How should portable class libraries look at this?

**Comment by SamuelEnglard** [comment]
Actually, that should be a separate issue

**Comment by sayedihashimi** [comment]
@SamuelEnglard thanks I'll delete the comments from here about PCL (_including this message_) to clean up this thread.

**Comment by sayedihashimi** [comment]
Assigning to @SamuelEnglard since he mentioned he was working on it.

**Comment by shmuelie** [comment]
This is now merged in
