### ISSUE TITLE
Add wiki info on how to contribute & release

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-csharp#6]
We should add wiki pages for the following.
- [x] How to contribute
- [x] How to release the generators

**Comment by sayedihashimi** [comment]
Added the following pages
- [How to conbribute](https://github.com/OmniSharp/generator-csharp/wiki/How-to-Contribute)
- [How to publish changes](https://github.com/OmniSharp/generator-aspnet/wiki/How-to-Publish-Changes)

@SamuelEnglard when you are ready to release take a look at the link above and then send a PR to the `release` branch. Thanks a lot for your help. Let me know if there is anything that you need from me.

**Comment by shmuelie** [comment]
Will do
